// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MeasurementService.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Measurement.Net {
  public static partial class MeasurementService
  {
    static readonly string __ServiceName = "measurement.MeasurementService";

    static readonly grpc::Marshaller<global::Measurement.Net.MeasurementData> __Marshaller_measurement_MeasurementData = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Measurement.Net.MeasurementData.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Measurement.Net.MeasurementResult> __Marshaller_measurement_MeasurementResult = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Measurement.Net.MeasurementResult.Parser.ParseFrom);

    static readonly grpc::Method<global::Measurement.Net.MeasurementData, global::Measurement.Net.MeasurementResult> __Method_Calculate = new grpc::Method<global::Measurement.Net.MeasurementData, global::Measurement.Net.MeasurementResult>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "Calculate",
        __Marshaller_measurement_MeasurementData,
        __Marshaller_measurement_MeasurementResult);

    static readonly grpc::Method<global::Measurement.Net.MeasurementData, global::Measurement.Net.MeasurementResult> __Method_CalculateStream = new grpc::Method<global::Measurement.Net.MeasurementData, global::Measurement.Net.MeasurementResult>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "CalculateStream",
        __Marshaller_measurement_MeasurementData,
        __Marshaller_measurement_MeasurementResult);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Measurement.Net.MeasurementServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MeasurementService</summary>
    [grpc::BindServiceMethod(typeof(MeasurementService), "BindService")]
    public abstract partial class MeasurementServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Measurement.Net.MeasurementResult> Calculate(grpc::IAsyncStreamReader<global::Measurement.Net.MeasurementData> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task CalculateStream(grpc::IAsyncStreamReader<global::Measurement.Net.MeasurementData> requestStream, grpc::IServerStreamWriter<global::Measurement.Net.MeasurementResult> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for MeasurementService</summary>
    public partial class MeasurementServiceClient : grpc::ClientBase<MeasurementServiceClient>
    {
      /// <summary>Creates a new client for MeasurementService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public MeasurementServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MeasurementService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public MeasurementServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected MeasurementServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected MeasurementServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncClientStreamingCall<global::Measurement.Net.MeasurementData, global::Measurement.Net.MeasurementResult> Calculate(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Calculate(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncClientStreamingCall<global::Measurement.Net.MeasurementData, global::Measurement.Net.MeasurementResult> Calculate(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_Calculate, null, options);
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Measurement.Net.MeasurementData, global::Measurement.Net.MeasurementResult> CalculateStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CalculateStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Measurement.Net.MeasurementData, global::Measurement.Net.MeasurementResult> CalculateStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_CalculateStream, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override MeasurementServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MeasurementServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(MeasurementServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Calculate, serviceImpl.Calculate)
          .AddMethod(__Method_CalculateStream, serviceImpl.CalculateStream).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, MeasurementServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Calculate, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::Measurement.Net.MeasurementData, global::Measurement.Net.MeasurementResult>(serviceImpl.Calculate));
      serviceBinder.AddMethod(__Method_CalculateStream, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::Measurement.Net.MeasurementData, global::Measurement.Net.MeasurementResult>(serviceImpl.CalculateStream));
    }

  }
}
#endregion
